//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class backuptable
    {
        public int ID { get; set; }
        public Nullable<int> QNPink { get; set; }
        public Nullable<int> QNWhite { get; set; }
        public Nullable<int> QNBlue { get; set; }
        public Nullable<int> QNRed { get; set; }
        public Nullable<int> QNYellow { get; set; }
        public Nullable<int> QNGreen { get; set; }
        public string UnitColor { get; set; }
        public string Service { get; set; }
        public string UID { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public string Course { get; set; }
        public string LastSchool { get; set; }
        public Nullable<System.DateTime> QDate { get; set; }
        public string Qstatus { get; set; }
        public string ClientType { get; set; }
    }
}
